### ISSUE TITLE
Sample using JDBC/JPA connection

### ISSUE THREAD

**Issue by lduparc** [micronaut-projects/micronaut-examples#16]
Hi everybody,

Is it possible to have an example with jdbc and/or jpa connection in java. 
Using     
```
compile "io.micronaut.configuration:hibernate-jpa"
runtime "io.micronaut.configuration:jdbc-tomcat"
```
I'm not able to run a call on my database with this configuration : 

```
datasources:
  default:
    url: jdbc:mariadb://dbre-mariadb01.cultura.intra:3306/products
    username: resilience
    password: "resilience"
    driverClassName: org.mariadb.jdbc.Driver

jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

```

I receive this error : `Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: TABLE is not mapped`

Regards
